In [1]:
import pandas as pd

In [2]:
# Read in the data
df = pd.read_csv(r'C:\Users\Jesus\Desktop\jesugit\data_1_checks\Hospital_Service_Area_2021.csv', low_memory=False)
zipdf = pd.read_excel(r'C:\Users\Jesus\Desktop\jesugit\data_1_checks\uszips.xlsx')

In [3]:
# Cleaning the data of "*" values
df = df[(df.TOTAL_DAYS_OF_CARE != "*") & (df.TOTAL_CHARGES != "*") &(df.TOTAL_CASES != "*") ]
# Keeping only the KY zip codes
KYdf = zipdf[zipdf.state_id == "KY"]

In [4]:
# Convert the data to string to merge
KYdf['zip'] = KYdf['zip'].astype(str)

# Changing the column names to merge
df.columns = ['Medicare_CCN', 'zip', 'Total_days',
       'Total_charges', 'Total_cases']

C:\Users\Jesus\AppData\Local\Temp\ipykernel_6760\2362822964.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  KYdf['zip'] = KYdf['zip'].astype(str)

In [5]:
# Merge the data
df1 = df.merge(KYdf, on='zip')

In [6]:
df1

,Medicare_CCN,zip,Total_days,Total_charges,Total_cases,lat,lng,city,state_id,state_name,...,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
0,180012,42784,644,4616131,116,37.45030,-85.92272,Upton,KY,Kentucky,...,2071.0,12.1,21099,Hart,"{""21099"": 39.47, ""21093"": 36.33, ""21123"": 24.2}",Hart|Hardin|Larue,21099|21093|21123,False,False,America/Chicago
1,183028,42784,110,241588,11,37.45030,-85.92272,Upton,KY,Kentucky,...,2071.0,12.1,21099,Hart,"{""21099"": 39.47, ""21093"": 36.33, ""21123"": 24.2}",Hart|Hardin|Larue,21099|21093|21123,False,False,America/Chicago
2,180012,42782,37,502685,11,37.34475,-85.63702,Summersville,KY,Kentucky,...,721.0,8.3,21087,Green,"{""21087"": 87.17, ""21099"": 12.83}",Green|Hart,21087|21099,False,False,America/Chicago
3,180087,42782,97,561464,15,37.34475,-85.63702,Summersville,KY,Kentucky,...,721.0,8.3,21087,Green,"{""21087"": 87.17, ""21099"": 12.83}",Green|Hart,21087|21099,False,False,America/Chicago
4,180012,42776,536,3827326,101,37.51577,-85.91834,Sonora,KY,Kentucky,...,2632.0,15.4,21093,Hardin,"{""21093"": 69.11, ""21123"": 30.89}",Hardin|Larue,21093|21123,False,False,America/New_York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2219,182001,40004,251,1912806,11,37.80279,-85.46950,Bardstown,KY,Kentucky,...,29892.0,79.4,21179,Nelson,"{""21179"": 100}",Nelson,21179,False,False,America/New_York
2220,183028,40004,305,664996,27,37.80279,-85.46950,Bardstown,KY,Kentucky,...,29892.0,79.4,21179,Nelson,"{""21179"": 100}",Nelson,21179,False,False,America/New_York
2221,180040,40003,99,1442160,11,38.26863,-85.04367,Bagdad,KY,Kentucky,...,2012.0,17.9,21211,Shelby,"{""21211"": 92.6, ""21073"": 7.4}",Shelby|Franklin,21211|21073,False,False,America/New_York
2222,180088,40003,116,1793644,17,38.26863,-85.04367,Bagdad,KY,Kentucky,...,2012.0,17.9,21211,Shelby,"{""21211"": 92.6, ""21073"": 7.4}",Shelby|Franklin,21211|21073,False,False,America/New_York
2223,180127,40003,125,1260939,16,38.26863,-85.04367,Bagdad,KY,Kentucky,...,2012.0,17.9,21211,Shelby,"{""21211"": 92.6, ""21073"": 7.4}",Shelby|Franklin,21211|21073,False,False,America/New_York